# nixpacks.toml

[phases.setup]
# Garante que as dependências padrão do PHP sejam incluídas
# e adiciona a extensão bcmath para a versão 8.2 do PHP
nixPkgs = ["...", "php82", "php82Extensions.bcmath"]

[start]
cmd = "php artisan serve --host 0.0.0.0 --port $PORT"